keys:
  - &master age193u8a6xha7vsmefmn4cnsz6refvaasszefzcm7e2pkhn6zsx2qyssda4lw
  - &vmware_stg age10xtc38nsfxxxmu8duu67595guq90pqvrw6ukee0e3y6sgcgwjqrsxwrfl7

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
        - *master
        - *vmware_stg
