keys:
  - &atolycs age1asmc3xd96e4xv8vwd8wk362dwxq8ydx5d5x0h4h0u59lz8eh4s9qhs9rcn
  - &atolycs_kvm age1jgzjnfvrfm5nhv3ew40kqfp4wlgdzm0p53y6ddk4j6kvcm4fhggsl6kaes
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|yml)$
    key_groups:
      - age:
         - *atolycs
         - *atolycs_kvm
