hello: ENC[AES256_GCM,data:FV5fIn+8faYthImXrRxtUg+8MhKtNAzm/MqTXfuvpJjQlCZwdYHSOtJv00r96Q==,iv:WASBza7vEWd2UlDEx+7X2NSkXn3kRDg1fPUy00CAfuw=,tag:YPB5cdeYTZwsFQNBxRop3Q==,type:str]
example_key: ENC[AES256_GCM,data:MJhnXR1Ethr41Nf4gw==,iv:w11y/DCm4LZYqsipWU8Azl4JrLBogw2VlX7Hdlg4J/8=,tag:T83uBTO2naOYEwEerxWjQA==,type:str]
test_code: ENC[AES256_GCM,data:XS35CBNHMg01P8aV,iv:RTDd5l9KzajDKCxuyqcnnZ8rksRJdu5XkmhM5W7MAOE=,tag:jA3LWxyoxqeR68Tv3UO5+w==,type:str]
#ENC[AES256_GCM,data:vR6PqJGODOHvARAklPN42g==,iv:jB+gARQaXuG3xU+TIYn7sNcddEA5Bu5RLSSXlwWKF5A=,tag:aJcfMG2XJHh7FF7tzoBqGw==,type:comment]
example_array:
    - ENC[AES256_GCM,data:kK5HlJenB4dNXg8zgvw=,iv:gYUQAKXX20c02yW8sS9jt0TBGrJsgiqaUlf2XU8g8rs=,tag:BKymV6XnEiO6mzv9AuqQiw==,type:str]
    - ENC[AES256_GCM,data:BpCCtF6E/pk0Dq9KPNQ=,iv:iTHktT923Ny7/+l+KrrMLxaiOHoesEFSpKDeVSQjR7o=,tag:N28XPBqYYtc/xEfWuitTkg==,type:str]
example_number: ENC[AES256_GCM,data:7No0ID6gmucLBQ==,iv:i7pVq0h77IzWiJeYtGlE6ONwiig3gH2Tq0/09kerOh8=,tag:pkeEMierA9O5AWyyasRSGg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:sAkx3g==,iv:GnkNw6bpMcOtdoNK2VZeFHIrlQWg+sE/cl4OvOSB76g=,tag:VYOpg0z4mJdyWVNxkhaNIw==,type:bool]
    - ENC[AES256_GCM,data:L9tJ3Jw=,iv:e1tg5Ruc8p4EBBmtwLiGfQMKtzOToW6IIyH+XeYYlK8=,tag:43mO/PwYJucCat4CHErJfQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age193u8a6xha7vsmefmn4cnsz6refvaasszefzcm7e2pkhn6zsx2qyssda4lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWVlVVjQxeTV6bEpJejRE
            MXFPL0pZb3ZYMnBIRE5sS3BWKzlpU0dDclQ0CmRqditNTGRLQS9HVk1Gb2tTYUFW
            cEV3ZDA0VmR5bm0vWjRvemFqSzZYVU0KLS0tIGloVm11KzU5UEU4U3FsUllDSTdB
            dmkxVFI0cHdEK2t4K3FQRE1zbEl2QkEK6y3uXFZnrcSGD05LnZNt8xONpKWOrdF8
            larYmnt2cNRCj6dB5N9D45kcP5l2Z8PjAZ+YtmZXPmzXST9xG4kPzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10xtc38nsfxxxmu8duu67595guq90pqvrw6ukee0e3y6sgcgwjqrsxwrfl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUmxtZmoxUmZiUWt6eFdE
            SkU4ZHdjRG56MTZkWUlKa09jN1duZmlTUm5VCmNudXpOMmNYSnV0K1FQcVM1a2Vw
            MWZ0WGkydmxmTlo0Qmd4MjVUdy9RbEUKLS0tIGV1YTJObEtpM25vOXh2YklOMm5u
            UDFqS3dSSVNKV1JFeUlncGU0dzV1ckEKt8VmAk6dI1SppOVGasWDNGho3gPL+NGP
            nRBC9YECr/Vl7DYOrja6hqjD+E78emaQgb49awgQwYZUJ48a3U6GHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T03:37:03Z"
    mac: ENC[AES256_GCM,data:gYDPOp2vePVI2RfGQm1lvFqtfPZP8Hw/zNiGfLqq5Nt2gqAB1aUC2e+eOnYClXom6dBpJIFxYL8AyN55DBtQGIYTqPplCxvmL259eMMnyfrHZd1ulZvbSHpGGvEHN2LFGC+7n45XUqLIJSOU9JL8c7teW+lQg02yt+t4TrXKlIA=,iv:zG4/yYwOYoHfZ8W2ytl7KzGu2xkXPuKLIglXnS0wpVA=,tag:F03psFIRVS3Np2lLDnrkXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
